### ISSUE TITLE
Can not install build tools 

### ISSUE THREAD

**Issue by trahoa** [soyoeml/transmission-2.93#1]
Hi @soyoeml 

I have an error when trying to run step 3 (install build tools):
ipkg-opt install gcc make p7zip openssl-dev libevent libcurl-dev zlib
(gcc not found)

I installed optware in my book live following this link: http://mybookworld.wikidot.com/optware

Could you tell me how did you install optware on your my book live, so that gcc could be found. 

Thank you,

**Comment by soyoeml** [comment]
The optware software package is out of maintenance. You need find somewhere.
